"use client"

import { useState } from "react"
import { ChevronDown } from 'lucide-react'

type FAQItem = {
  question: string
  answer: string
}

export function FAQSection() {
  const [openIndex, setOpenIndex] = useState<number | null>(null)

  const toggleFAQ = (index: number) => {
    setOpenIndex(openIndex === index ? null : index)
  }

  const faqItems: FAQItem[] = [
    {
      question: "Are the articles copyright/plagiarism free?",
      answer: "Yes, all articles generated by GetMoreSEO are 100% original and plagiarism-free. Our AI creates unique content that passes plagiarism checks. You receive full copyright ownership of all content generated through our platform."
    },
    {
      question: "Can Google tell if an article is written by AI?",
      answer: "Google's primary focus is on content quality, not how it was created. GetMoreSEO uses advanced AI humanization technology that makes content indistinguishable from human-written text. Our content is designed to meet Google's quality guidelines by being helpful, reliable, and people-first."
    },
    {
      question: "Can I choose to edit the articles before they go live?",
      answer: "GetMoreSEO gives you complete control over your content. You can review and edit any article before it's published. Our platform includes a built-in editor that allows you to make changes, add personal touches, or adjust the content to better match your brand voice."
    },
    {
      question: "Can I customize the structure of the articles?",
      answer: "Yes, GetMoreSEO offers extensive customization options for article structure. You can define custom templates, specify heading structures, determine content length, and set the tone and style. This ensures all generated content aligns perfectly with your brand guidelines and content strategy."
    },
    {
      question: "Can I integrate with other platforms?",
      answer: "GetMoreSEO seamlessly integrates with most popular content management systems and blogging platforms including WordPress, Shopify, Webflow, Wix, Ghost, and more. We also support Zapier integration, allowing you to connect with thousands of other apps and automate your content workflow."
    },
    {
      question: "Can I post the generated blog directly to my website?",
      answer: "Yes! GetMoreSEO offers direct publishing capabilities to most major platforms. Once you've approved an article, you can publish it immediately or schedule it for later with just a few clicks. This eliminates the need to manually copy and paste content between systems."
    },
    {
      question: "Can I use AI to write an article?",
      answer: "Yes, that's exactly what GetMoreSEO is designed for. Our AI writing technology can generate high-quality, SEO-optimized articles on virtually any topic. Simply provide a keyword or topic, and our AI will create engaging, informative content tailored to your needs."
    },
    {
      question: "Can I use this for multiple sites?",
      answer: "Yes, GetMoreSEO supports multiple websites under a single account. Our higher-tier plans allow you to manage content for different websites, each with its own settings, publishing schedules, and integration preferences. This makes it perfect for agencies or businesses managing multiple brands."
    },
    {
      question: "Do the generated blog post include images, videos and links?",
      answer: "GetMoreSEO can suggest relevant images for your articles and automatically insert internal and external links based on your preferences. While we don't create videos, our system can embed existing videos from platforms like YouTube when relevant to your content. You can also manually add any media elements during the editing process."
    },
    {
      question: "Do you have an affiliate program?",
      answer: "Yes, we have a generous affiliate program that rewards you for referring new customers to GetMoreSEO. You'll earn a commission on qualifying purchases made by the users you refer. Visit our Affiliate Program page to learn more about commission rates and how to join."
    },
    {
      question: "Do you support internal & external linking?",
      answer: "Yes, GetMoreSEO supports both internal and external linking. Our AI can automatically suggest and insert relevant internal links to other pages on your website to improve SEO and user experience. You can also set preferences for external linking to authoritative sources to enhance content credibility."
    },
    {
      question: "Does Google penalize AI content?",
      answer: "Google penalizes low-quality content, regardless of how it's created. GetMoreSEO produces high-quality, valuable content that follows Google's guidelines. Our AI humanization technology ensures the content reads naturally and provides genuine value to readers, which is what Google rewards in its rankings."
    },
    {
      question: "Does GetMoreSEO pass AI detectors?",
      answer: "Yes, content created with GetMoreSEO is designed to pass AI detection tools. Our advanced AI humanization technology creates content that is indistinguishable from human-written text. This helps ensure your content appears natural and authentic to both readers and detection systems."
    },
    {
      question: "Is it legal to use AI to write articles?",
      answer: "Yes, using AI to generate content is completely legal. However, as with any content, you should ensure it doesn't violate copyright laws or contain false information. GetMoreSEO helps you create original content that you own the rights to once it's generated."
    },
    {
      question: "How is this different from ChatGPT and other AI writers?",
      answer: "Unlike general-purpose AI like ChatGPT, GetMoreSEO is specifically designed for SEO-focused content creation. We offer specialized features like keyword optimization, automatic publishing, internal linking, and content that's structured to rank well in search engines. Our platform also includes AI humanization technology and integrates directly with your website, creating a complete content production system rather than just a text generator."
    },
    {
      question: "How does the Google Auto Indexing work?",
      answer: "GetMoreSEO helps your content get indexed faster by Google through several techniques: we generate XML sitemaps, implement proper schema markup, ensure mobile-friendly content, and optimize internal linking structures. While we can't guarantee immediate indexing (as that's ultimately controlled by Google), our methods significantly improve the discovery and indexing process for your content."
    }
  ]

  return (
    <section className="py-16 md:py-24">
      <div className="max-w-7xl mx-auto px-4">
        <div className="text-center mb-12 md:mb-16">
          <h2 className="text-3xl md:text-4xl font-bold mb-4">Frequently Asked Questions</h2>
          <p className="text-gray-600 max-w-2xl mx-auto">
            Everything you need to know about GetMoreSEO and how it can help grow your business.
          </p>
        </div>

        <div className="grid md:grid-cols-2 gap-6">
          {faqItems.map((item, index) => (
            <div 
              key={index} 
              className="bg-white rounded-xl shadow-sm border border-gray-100 overflow-hidden"
            >
              <button
                className="w-full px-6 py-4 text-left flex justify-between items-center"
                onClick={() => toggleFAQ(index)}
                aria-expanded={openIndex === index}
              >
                <span className="font-medium text-gray-900">{item.question}</span>
                <ChevronDown 
                  className={`h-5 w-5 text-gray-500 transition-transform ${
                    openIndex === index ? "transform rotate-180" : ""
                  }`} 
                />
              </button>
              
              {openIndex === index && (
                <div className="px-6 pb-4">
                  <p className="text-gray-600">{item.answer}</p>
                </div>
              )}
            </div>
          ))}
        </div>
      </div>
    </section>
  )
}
