"use client"

import { useState } from "react"
import { ChevronDown, ArrowRight } from "lucide-react"

export default function FAQSection() {
  const [openIndex, setOpenIndex] = useState<number | null>(null)

  const faqs = [
    {
      question: "How much time will I need to spend managing the system?",
      answer:
        "None. Our 100% autopilot approach means you can set your preferences once and let the system handle everything else.",
    },
    {
      question: "Will the content actually sound human?",
      answer:
        "Yes! Our AI is specifically trained to create fully humanized content that reads naturally and engages readers effectively.",
    },
    {
      question: "How does GetMoreSEO compare to hiring a content writer?",
      answer:
        "GetMoreSEO costs approximately 1/5th of hiring professional writers while delivering consistent, SEO-optimized content without management overhead.",
    },
    {
      question: "Can I edit the content if needed?",
      answer:
        "Absolutely. While the system works autonomously, you always have the option to review and edit any post before or after publishing.",
    },
    {
      question: "Will these blogs actually rank on Google?",
      answer:
        "Yes. Our system follows all of Google's E-E-A-T guidelines and creates content specifically designed to perform well in search rankings.",
    },
    {
      question: "Are the articles copyright/plagiarism free?",
      answer:
        "Absolutely. All content generated by GetMoreSEO is 100% original and passes plagiarism checks. We use advanced AI models trained to create unique content, not copy existing material.",
    },
    {
      question: "Can Google tell if an article is written by AI?",
      answer:
        "No. Our content is indistinguishable from human-written content because it's specifically designed to meet Google's quality standards with proper structure, natural language patterns, and expert-level insights.",
    },
    {
      question: "Can I choose to edit the articles before they go live?",
      answer:
        "Yes. You have complete control over the publishing workflow. You can set the system to automatically publish or enable a review step where you can edit content before it goes live.",
    },
    {
      question: "Can I customize the structure of the articles?",
      answer:
        "Definitely. You can set your preferred article structure, including heading formats, content length, tone of voice, and specific sections you want included in every post.",
    },
    {
      question: "Can I integrate with other platforms?",
      answer:
        "Yes. GetMoreSEO integrates seamlessly with WordPress, Shopify, Wix, and most major CMS platforms. We also offer API access for custom integrations with your existing systems.",
    },
  ]

  // This function ensures only one FAQ is open at a time
  const toggleFaq = (index: number) => {
    setOpenIndex(openIndex === index ? null : index)
  }

  return (
    <section className="py-24 bg-white relative overflow-hidden">
      <div className="absolute top-40 left-0 w-72 h-72 bg-[#294df6]/5 rounded-full blur-3xl"></div>
      <div className="absolute bottom-20 right-0 w-80 h-80 bg-[#294df6]/5 rounded-full blur-3xl"></div>

      <div className="max-w-7xl mx-auto px-4">
        <div className="text-center mb-16">
          <h2 className="text-3xl md:text-4xl lg:text-5xl font-bold mb-6 text-gray-800">Frequently Asked Questions</h2>
        </div>

        <div className="grid md:grid-cols-2 gap-6 mb-16">
          {faqs.map((faq, i) => (
            <div
              key={i}
              className="bg-white rounded-xl border border-gray-200 overflow-hidden hover:border-[#294df6]/30 transition-all duration-300"
            >
              <button
                className="w-full text-left px-6 py-5 flex items-center justify-between focus:outline-none"
                onClick={() => toggleFaq(i)}
                aria-expanded={openIndex === i}
                aria-controls={`faq-answer-${i}`}
              >
                <span className="font-medium text-gray-800">{faq.question}</span>
                <ChevronDown
                  className={`h-5 w-5 text-gray-500 transition-transform duration-300 flex-shrink-0 ${
                    openIndex === i ? "transform rotate-180" : ""
                  }`}
                />
              </button>
              <div
                id={`faq-answer-${i}`}
                className={`overflow-hidden transition-all duration-300 ease-in-out ${
                  openIndex === i ? "max-h-[500px] opacity-100" : "max-h-0 opacity-0"
                }`}
              >
                <div className="px-6 pb-5 pt-1">
                  <p className="text-gray-600">{faq.answer}</p>
                </div>
              </div>
            </div>
          ))}
        </div>

       
      </div>
    </section>
  )
}
